version: '3'
services:
  mysql-standalone:
    container_name: mysql-standalone
    image: 'mysql:8.0.23'
    restart: always
    networks:
      - mysql-standalone-network
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
  producer-consumer-service:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    image: producer-consumer-service
    restart: on-failure
    networks:
      - mysql-standalone-network
    container_name: producer-consumer-service
    ports:
      - "8086:8086"
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
    depends_on:
      - mysql-standalone
networks:
  mysql-standalone-network:
    driver: bridge