spring:
  datasource:
    url: jdbc:mysql://mysql-standalone:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    show-sql: true
server:
  port: 8086
app:
  counterMin: 0
  counterMax: 100